# @package hydra.launcher

# /home/lombardi/Projects/PoET/train/configs/hydra/launcher/default.yaml
defaults:
  - submitit_slurm

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
timeout_min: 4320 # 3 days, time limit must be set in minutes
nodes: 1
tasks_per_node: 1
gpus_per_node: 1
name: ${hydra.job.name}
